title: "Data Analyst Portfolio"
description: "Showcasing my projects, skills, and accomplishments in data analysis."
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Optional: Customize the theme
theme_config:
  social_links:
    - name: "GitHub"
      url: "https://github.com/your-username"
    - name: "LinkedIn"
      url: "https://linkedin.com/in/your-profile"
  logo: "/assets/images/logo.png" # Add your logo file here
  search_enabled: true
