title: "Data Analyst Portfolio"
description: "Showcasing my projects, skills, and accomplishments in data analysis."
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
